import type { Metadata } from "next";
import "../styles/globals.css";

import { SidebarProvider, SidebarTrigger } from "@/components/ui/sidebar";
import { AppSidebar } from "@/components/app-sidebar";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html>
      <body className="flex min-h-screen">
        <SidebarProvider>
          <main className="w-full">{children}</main>
        </SidebarProvider>
      </body>
    </html>
  );
}
